package com.doing.blog.model;

import java.util.Date;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_admin.a_id
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    private String aId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_admin.login_name
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_admin.username
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_admin.password
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_admin.sex
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_admin.birthday
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_admin.create_date
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_admin.phone
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_admin.visits_number
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    private Long visitsNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_admin.a_id
     *
     * @return the value of blog_admin.a_id
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public String getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_admin.a_id
     *
     * @param aId the value for blog_admin.a_id
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public void setaId(String aId) {
        this.aId = aId == null ? null : aId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_admin.login_name
     *
     * @return the value of blog_admin.login_name
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_admin.login_name
     *
     * @param loginName the value for blog_admin.login_name
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_admin.username
     *
     * @return the value of blog_admin.username
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_admin.username
     *
     * @param username the value for blog_admin.username
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_admin.password
     *
     * @return the value of blog_admin.password
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_admin.password
     *
     * @param password the value for blog_admin.password
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_admin.sex
     *
     * @return the value of blog_admin.sex
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_admin.sex
     *
     * @param sex the value for blog_admin.sex
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_admin.birthday
     *
     * @return the value of blog_admin.birthday
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_admin.birthday
     *
     * @param birthday the value for blog_admin.birthday
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_admin.create_date
     *
     * @return the value of blog_admin.create_date
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_admin.create_date
     *
     * @param createDate the value for blog_admin.create_date
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_admin.phone
     *
     * @return the value of blog_admin.phone
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_admin.phone
     *
     * @param phone the value for blog_admin.phone
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_admin.visits_number
     *
     * @return the value of blog_admin.visits_number
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public Long getVisitsNumber() {
        return visitsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_admin.visits_number
     *
     * @param visitsNumber the value for blog_admin.visits_number
     *
     * @mbggenerated Sat Aug 27 14:10:10 CST 2016
     */
    public void setVisitsNumber(Long visitsNumber) {
        this.visitsNumber = visitsNumber;
    }
}