package com.doing.blog.model;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.article_id
     *
     * @mbggenerated Thu Aug 25 16:02:27 CST 2016
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.title
     *
     * @mbggenerated Thu Aug 25 16:02:27 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.create_date
     *
     * @mbggenerated Thu Aug 25 16:02:27 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.visits_number
     *
     * @mbggenerated Thu Aug 25 16:02:27 CST 2016
     */
    private Long visitsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.content
     *
     * @mbggenerated Thu Aug 25 16:02:27 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.article_id
     *
     * @return the value of blog_article.article_id
     *
     * @mbggenerated Thu Aug 25 16:02:27 CST 2016
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.article_id
     *
     * @param articleId the value for blog_article.article_id
     *
     * @mbggenerated Thu Aug 25 16:02:27 CST 2016
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.title
     *
     * @return the value of blog_article.title
     *
     * @mbggenerated Thu Aug 25 16:02:27 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.title
     *
     * @param title the value for blog_article.title
     *
     * @mbggenerated Thu Aug 25 16:02:27 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.create_date
     *
     * @return the value of blog_article.create_date
     *
     * @mbggenerated Thu Aug 25 16:02:27 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.create_date
     *
     * @param createDate the value for blog_article.create_date
     *
     * @mbggenerated Thu Aug 25 16:02:27 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.visits_number
     *
     * @return the value of blog_article.visits_number
     *
     * @mbggenerated Thu Aug 25 16:02:27 CST 2016
     */
    public Long getVisitsNumber() {
        return visitsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.visits_number
     *
     * @param visitsNumber the value for blog_article.visits_number
     *
     * @mbggenerated Thu Aug 25 16:02:27 CST 2016
     */
    public void setVisitsNumber(Long visitsNumber) {
        this.visitsNumber = visitsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.content
     *
     * @return the value of blog_article.content
     *
     * @mbggenerated Thu Aug 25 16:02:27 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.content
     *
     * @param content the value for blog_article.content
     *
     * @mbggenerated Thu Aug 25 16:02:27 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}