package com.doing.blog.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.u_id
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    private String uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.login_name
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.username
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.password
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.sex
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.birthday
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.phone
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.create_date
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.head_portrait
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    private String headPortrait;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.u_id
     *
     * @return the value of blog_user.u_id
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.u_id
     *
     * @param uId the value for blog_user.u_id
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.login_name
     *
     * @return the value of blog_user.login_name
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.login_name
     *
     * @param loginName the value for blog_user.login_name
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.username
     *
     * @return the value of blog_user.username
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.username
     *
     * @param username the value for blog_user.username
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.password
     *
     * @return the value of blog_user.password
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.password
     *
     * @param password the value for blog_user.password
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.sex
     *
     * @return the value of blog_user.sex
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.sex
     *
     * @param sex the value for blog_user.sex
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.birthday
     *
     * @return the value of blog_user.birthday
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.birthday
     *
     * @param birthday the value for blog_user.birthday
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.phone
     *
     * @return the value of blog_user.phone
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.phone
     *
     * @param phone the value for blog_user.phone
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.create_date
     *
     * @return the value of blog_user.create_date
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.create_date
     *
     * @param createDate the value for blog_user.create_date
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.head_portrait
     *
     * @return the value of blog_user.head_portrait
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public String getHeadPortrait() {
        return headPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.head_portrait
     *
     * @param headPortrait the value for blog_user.head_portrait
     *
     * @mbggenerated Sun Aug 21 16:09:24 CST 2016
     */
    public void setHeadPortrait(String headPortrait) {
        this.headPortrait = headPortrait == null ? null : headPortrait.trim();
    }
}