package com.doing.blog.model;

import java.util.Date;
import java.util.List;

public class UserComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.ucomment_id
     *
     * @mbggenerated Sun Aug 28 00:31:59 CST 2016
     */
    private Long ucommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.create_time
     *
     * @mbggenerated Sun Aug 28 00:31:59 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.user_id
     *
     * @mbggenerated Sun Aug 28 00:31:59 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.article_id
     *
     * @mbggenerated Sun Aug 28 00:31:59 CST 2016
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.content
     *
     * @mbggenerated Sun Aug 28 00:31:59 CST 2016
     */
    private String content;

    /**
     * 一条用户评论只有一个用户发表，一对一
     */
    private User user;

    /**
     * 一条用户评论可以评论多篇博客文章，一对多
     */
    private List<Article> articleList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.ucomment_id
     *
     * @return the value of user_comment.ucomment_id
     *
     * @mbggenerated Sun Aug 28 00:31:59 CST 2016
     */
    public Long getUcommentId() {
        return ucommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.ucomment_id
     *
     * @param ucommentId the value for user_comment.ucomment_id
     *
     * @mbggenerated Sun Aug 28 00:31:59 CST 2016
     */
    public void setUcommentId(Long ucommentId) {
        this.ucommentId = ucommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.create_time
     *
     * @return the value of user_comment.create_time
     *
     * @mbggenerated Sun Aug 28 00:31:59 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.create_time
     *
     * @param createTime the value for user_comment.create_time
     *
     * @mbggenerated Sun Aug 28 00:31:59 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.user_id
     *
     * @return the value of user_comment.user_id
     *
     * @mbggenerated Sun Aug 28 00:31:59 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.user_id
     *
     * @param userId the value for user_comment.user_id
     *
     * @mbggenerated Sun Aug 28 00:31:59 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.article_id
     *
     * @return the value of user_comment.article_id
     *
     * @mbggenerated Sun Aug 28 00:31:59 CST 2016
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.article_id
     *
     * @param articleId the value for user_comment.article_id
     *
     * @mbggenerated Sun Aug 28 00:31:59 CST 2016
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.content
     *
     * @return the value of user_comment.content
     *
     * @mbggenerated Sun Aug 28 00:31:59 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.content
     *
     * @param content the value for user_comment.content
     *
     * @mbggenerated Sun Aug 28 00:31:59 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public List<Article> getArticleList() {
        return articleList;
    }

    public void setArticleList(List<Article> articleList) {
        this.articleList = articleList;
    }
}