package com.doing.blog.mapper;

import com.doing.blog.model.BlogAdmin;
import com.doing.blog.model.BlogAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_admin
     *
     * @mbggenerated Fri Aug 05 13:27:49 CST 2016
     */
    int countByExample(BlogAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_admin
     *
     * @mbggenerated Fri Aug 05 13:27:49 CST 2016
     */
    int deleteByExample(BlogAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_admin
     *
     * @mbggenerated Fri Aug 05 13:27:49 CST 2016
     */
    int deleteByPrimaryKey(String uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_admin
     *
     * @mbggenerated Fri Aug 05 13:27:49 CST 2016
     */
    int insert(BlogAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_admin
     *
     * @mbggenerated Fri Aug 05 13:27:49 CST 2016
     */
    int insertSelective(BlogAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_admin
     *
     * @mbggenerated Fri Aug 05 13:27:49 CST 2016
     */
    List<BlogAdmin> selectByExample(BlogAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_admin
     *
     * @mbggenerated Fri Aug 05 13:27:49 CST 2016
     */
    BlogAdmin selectByPrimaryKey(String uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_admin
     *
     * @mbggenerated Fri Aug 05 13:27:49 CST 2016
     */
    int updateByExampleSelective(@Param("record") BlogAdmin record, @Param("example") BlogAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_admin
     *
     * @mbggenerated Fri Aug 05 13:27:49 CST 2016
     */
    int updateByExample(@Param("record") BlogAdmin record, @Param("example") BlogAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_admin
     *
     * @mbggenerated Fri Aug 05 13:27:49 CST 2016
     */
    int updateByPrimaryKeySelective(BlogAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_admin
     *
     * @mbggenerated Fri Aug 05 13:27:49 CST 2016
     */
    int updateByPrimaryKey(BlogAdmin record);
}