<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>H+后台模板js文件集合</title>
</head>
<script src="${pageContext.request.contextPath}/resources/admin/js/jquery-2.1.1.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/jquery-ui-1.10.4.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/jquery-ui.custom.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/bootstrap.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/hplus.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/chartJs/Chart.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/chosen/chosen.jquery.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/codemirror/codemirror.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/codemirror/mode/javascript/javascript.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/colorpicker/bootstrap-colorpicker.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/datapicker/bootstrap-datepicker.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/dataTables/dataTables.bootstrap.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/dataTables/jquery.dataTables.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/dropzone/dropzone.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/easypiechart/jquery.easypiechart.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/echarts/echarts-all.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/fancybox/jquery.fancybox.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/flot/curvedLines.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/flot/jquery.flot.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/flot/jquery.flot.pie.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/flot/jquery.flot.resize.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/flot/jquery.flot.spline.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/flot/jquery.flot.symbol.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/flot/jquery.flot.tooltip.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/gritter/jquery.gritter.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/ionRangeSlider/ion.rangeSlider.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/jasny/jasny-bootstrap.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/jeditable/jquery.jeditable.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/jqgrid/jquery.jqGrid.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/jqgrid/i18n/grid.locale-cn.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/jsKnob/jquery.knob.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/jsTree/jstree.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/markdown/bootstrap-markdown.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/markdown/bootstrap-markdown.zh.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/markdown/markdown.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/markdown/to-markdown.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/metisMenu/jquery.metisMenu.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/morris/morris.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/morris/raphael-2.1.0.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/nestable/jquery.nestable.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/nouslider/jquery.nouislider.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/pace/pace.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/rickshaw/vendor/d3.v3.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/simditor/hotkeys.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/simditor/module.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/simditor/simditor.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/simditor/uploader.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/staps/jquery.steps.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/summernote/summernote.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/summernote/summernote-zh-CN.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/switchery/switchery.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/toastr/toastr.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/treeview/bootstrap-treeview.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/validate/jquery.validate.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/validate/messages_zh.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/webuploader/webuploader.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/layer/laydate/laydate.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/layer/layim/layim.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/resources/admin/js/plugins/layer/layer.min.js" type="text/javascript"></script>
</html>